CREATE DATABASE [GSC_CalleLarga_QA]
 CONTAINMENT = NONE
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET ARITHABORT OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET  READ_WRITE 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET RECOVERY FULL 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET  MULTI_USER 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GSC_CalleLarga_QA] SET DELAYED_DURABILITY = DISABLED 
GO
USE [GSC_CalleLarga_QA]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [GSC_CalleLarga_QA]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [GSC_CalleLarga_QA] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
